on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Espanso Validator
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Hello world action step
        id: espanso-validate
        uses: 4lch4/Espanso-Validator@v0.0.23

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.espanso-validate.timeStart }}"

      - name: Get the file count
        run: echo "The time was ${{ steps.hello.espanso-validate.fileCount }}"